server {
  listen 80;
  server_name _;
  sendfile off;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /cards.json {
    alias /voca-data/cards.json;
    add_header Cache-Control "no-store";
  }

  location /cards/ {
    alias /voca-data/cards/;
    autoindex on;
    add_header Cache-Control "no-store";
  }

  location /audio/ {
    alias /voca-data/audio/;
    autoindex on;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
